name: DominicSoon
favicon: null
layout_spectrum: 0.95377
typography_spectrum: 0.9455375962425023
title: Dominic Soon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bbbbbb'
    - '#444444'
    - '#777777'
  brandStrength: 0.1075937058776617
  lightness: 0.20503539289347827
  saturation: 0.30732396245002747
  rhythmicContrast: 0.483117658412084
purpose: []
